#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint:staged

envFile=.envrc

src/bin/run $envFile template$envFile
src/bin/run -f md $envFile template$envFile.md
# not auto-staging files to prevent 
# secrets getting committed by accident
# git add $envFile-template
