name: test-workflow

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Run tests
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install deps
        run: npm ci

      - name: check audits
        run: npm audit

      - name: install package for npx tests
        run: npm i -g file:./

      - name: run tests
        env:
          GEN_ENV_TEMPLATE_BASE: ${{ github.GITHUB_WORKSPACE }}
          GEN_ENV_TEMPLATE_ABSOLUTE_PATH: ${{ github.GITHUB_WORKSPACE }}/src/bin/run
        run: npm run test:ci
